### PR TITLE
Revert "Fixed broken link in README"

### PR DESCRIPTION
**Pull request by teixeirak**
Reverts SCBI-ForestGEO/SCBI-ForestGEO-Data#19

### CODE REVIEW

**Comment by teixeirak** [comment]
Hi @rudeboybert, I initially accepted this pull request to review more easily, but don't want to keep it in the master repository as is. We're wanting to keep that very clearly organized. You might create a branch, or alternatively we can discuss what you're hoping to do with this merge.

**Comment by rudeboybert** [comment]
Hi @teixeirak, nice to meet you. I had no other plans further than fixing the broken URL to the UTM Coordinates of SCBI plot corners folder. I'm happy to follow whatever workflow you folks have in mind (such as branch -> PR -> merge -> delete branch), and no worries if you'd rather revert.

**Comment by rudeboybert** [comment]
And apologies for being overly forward in making this PR without reaching out to you first.

**Comment by teixeirak** [comment]
Thanks for clarifying. The pull request actually pulled in your whole folder with multiple files. I'll be happy to merge just the fixed link. Thanks for catching it!

**Comment by rudeboybert** [comment]
Oh, my apologies! Yes, please revert this PR and I will resubmit with just the `README.md` URL fix!

**Comment by teixeirak** [comment]
I just fixed this. Thanks for catching it, and for your interest in the data. Feel free to contact me with any questions.

**Pull request merged**
